/**
 * images required throughout the app
 */
export const IMAGES = {
  noProducts: require('@/assets/images/noproduct.png'),
  noOrders: require('@/assets/images/noorder.png'),
  noCategories: require('@/assets/images/nocategory.png'),
  noCustomers: require('@/assets/images/nocustomer.png'),
  noSearch: require('@/assets/images/nosearch.png'),
  printerBanner: require('@/assets/images/banner2.png'),
  printerImage: require('@/assets/images/printerimage.png'),
  banner1: require('@/assets/images/banner1.png'),
  banner2: require('@/assets/images/banner2.png'),
  banner3: require('@/assets/images/banner3.png'),
  contactWhatsapp: require('@/assets/images/contact.png'),
  calendar: require('@/assets/images/calendar.png'),
  // printer: require('.@/assets/mages/printer.png'),
  bluetooth: require('@/assets/images/bluetooth.png'),
  placeholder: require('@/assets/images/placeholder.png'),
  // cancel: require('@/assets/mages/cancel.png'),
  megaphone: require('@/assets/images/megaphonebig.png'),
  activeDashboard: require('@/assets/images/dashboard_.png'),
  inActiveDashboard: require('@/assets/images/dashboard.png'),
  activeProducts: require('@/assets/images/products_.png'),
  inActiveProducts: require('@/assets/images/products.png'),
  activeOrders: require('@/assets/images/orders_.png'),
  inactiveOrders: require('@/assets/images/orders.png'),
  activeCustomers: require('@/assets/images/customers_.png'),
  inactiveCustomers: require('@/assets/images/customers.png'),
  activeMore: require('@/assets/images/more_.png'),
  inactiveMore: require('@/assets/images/more.png'),
  arrowDown: require('@/assets/images/down.png'),
  arrowUp: require('@/assets/images/up.png'),
  arrowRightWhite: require('@/assets/images/whitearrowright.png'),
  successImage: require('@/assets/images/successimage.png'),
  tinyStoreBanner: require('@/assets/images/storetiny.png'),
  copyImage: require('@/assets/images/copy.png'),
  shareImage: require('@/assets/images/share.png'),
  arrowRight: require('@/assets/images/arrowright.png'),
  arrowLeft: require('@/assets/images/arrowleft.png'),
  makeMoney: require('@/assets/images/makemoney.png'),
  storeSetup: require('@/assets/images/storesetup.png'),
  urlError: require('@/assets/images/urlerror.png'),
  urlGood: require('@/assets/images/urlgood.png'),
  edit: require('@/assets/images/edit.png'),
  basicSettings: require('@/assets/images/basicsettings.png'),
  camera: require('@/assets/images/camera.png'),
  eye: require('@/assets/images/eye.png'),
  shipping: require('@/assets/images/shipping.png'),
  storebg_angle: require('@/assets/images/storebg.png'),
  arrowRight_: require('@/assets/images/arrow_right.png'),
  analyticsImage: require('@/assets/images/analytics.png'),
  marketingImage: require('@/assets/images/marketing.png'),
  settingsImage: require('@/assets/images/settings.png'),
  dispatchImage: require('@/assets/images/dispatch.png'),
  storeDetailsImage: require('@/assets/images/basicsettings.png'),
  storeShippingImage: require('@/assets/images/shipping.png'),
  storePaymentImage: require('@/assets/images/payment.png'),
  moreStoreOptionsImage: require('@/assets/images/morestoreoptions.png'),
  faqImage: require('@/assets/images/faq.png'),
  themeImage: require('@/assets/images/theme.png'),
  twitter: require('@/assets/images/twitter.png'),
  facebook: require('@/assets/images/fb.png'),
  instagram: require('@/assets/images/insta.png'),
  security: require('@/assets/images/security.png'),
  rider: require('@/assets/images/rider.png'),
  discount: require('@/assets/images/discount.png'),
  inActiveFeeds: require('@/assets/images/feeds.png'),
  activeFeeds: require('@/assets/images/feeds_.png'),
  inActiveLive: require('@/assets/images/live.png'),
  activeLive: require('@/assets/images/live_.png'),
  inActiveShorts: require('@/assets/images/shorts.png'),
  activeShorts: require('@/assets/images/shorts_.png'),
  inActiveMessage: require('@/assets/images/message.png'),
  activeMessage: require('@/assets/images/message_.png'),
  // printer_: require('@/assets/images/printer.png')
};
